server:
  port: 8765

spring:
  application:
    name: gateway-server

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: ppchallenge
            client-name: ppchallenge-client
            client-id: ppchallenge-client
            client-secret: SrHCWBpHouNKqWvuZCC7StaUvVlV2MRa
            scope: openid,offline_access,profile
            redirect-uri: http://localhost:8765
            authorization-grant-type: authorization_code
        provider:
          ppchallenge:
            issuer-uri: ${KEYCLOCK_URL:http://localhost:9999/realms/ppchallenge}

  cloud:
    gateway:
      routes:
        - id: ms-transfer
          uri: lb://ms-transfer
          predicates:
            - Path=/ms-transfer/**
          filters:
            TokenRelay=

        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/ms-user/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      httpclient:
        connect-timeout: 5000
        response-timeout: 5s

      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        - RemoveRequestHeader=Authorization

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost}:${EUREKA_SERVER_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    hostname: ${EUREKA_HOST_NAME:localhost}
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
